feat(field_attributes): add helper functions
iddm/serde-aux pull request #41
Opened 2024-02-24 21:41 UTC by lucatrv

2024-04-21 12:47 UTC, iddm commented on src/field_attributes.rs
> +/// let s = r#" { "i64_or_f64": 1, "f64_or_string": 1 } "#;
I do not think `1` is a valid `f64` number, as it has no valid representation in the floating point value specification. I think the parser should have failed. I understand this is not how serde works here, but this might be confusing. Can we do something about it? I don't think so. Can you think of any possible improvement here?

2024-04-21 12:47 UTC, iddm commented on src/field_attributes.rs
> +pub fn deserialize_to_type_or_fallback<'de, D, T, F>(
I understand that this implementation was quite easy to implement this way, but I do not really like using the `Result` type for this matter. I wish we introduced another generic enum of our own to clearly designate the purpose (and the context), something like:

```rust
enum Either<FirstType, SecondType> {
    First(FirstType),
    Second(SecondType),
}
```
What do you think about that?

2024-04-21 12:47 UTC, iddm commented on src/field_attributes.rs
> +pub fn deserialize_to_type_or_string_lossy<'de, D, T>(
Should we have something like that but also returning just the byte array of the input instead? Perhaps, it could be more useful in some cases than a string? What do you think?

2024-04-21 12:47 UTC, iddm commented on src/field_attributes.rs
> +    Ok(result)
All the branches of this code lead to an immediate return, we can just
```rust
T::deserialize(value.clone()).map_err(|_| match value {
        serde_value::Value::Bool(b) => b.to_string(),
        serde_value::Value::U8(u) => u.to_string(),
        serde_value::Value::U16(u) => u.to_string(),
        serde_value::Value::U32(u) => u.to_string(),
        serde_value::Value::U64(u) => u.to_string(),
        serde_value::Value::I8(i) => i.to_string(),
        serde_value::Value::I16(i) => i.to_string(),
        serde_value::Value::I32(i) => i.to_string(),
        serde_value::Value::I64(i) => i.to_string(),
        serde_value::Value::F32(f) => f.to_string(),
        serde_value::Value::F64(f) => f.to_string(),
        serde_value::Value::Char(c) => c.to_string(),
        serde_value::Value::String(s) => s,
        serde_value::Value::Unit => String::new(),
        serde_value::Value::Option(opt) => {
            format!("{:?}", opt)
        }
        serde_value::Value::Newtype(nt) => {
            format!("{:?}", nt)
        }
        serde_value::Value::Seq(seq) => format!("{:?}", seq),
        serde_value::Value::Map(map) => format!("{:?}", map),
        serde_value::Value::Bytes(v) => String::from_utf8_lossy(&v).into_owned(),
    })
```

2024-04-21 12:47 UTC, iddm commented on src/field_attributes.rs
> +        T: Deserialize<'de>,
Why was this and other similar changes necessary? Did `cargo fmt`, or `cargo clippy`, or `rustc` complain about that?

2024-04-21 12:47 UTC, iddm commented on src/field_attributes.rs
> +    });
It looks like we can achieve the same result using either the deserialisation to `serde_json::Value` or implementing all these functions manually instead of using (and relying) on an old and, possibly, unmaintained crate such as `serve-value`. I also think that the less unreasonable dependencies there are in the dependency tree, the better it is for many various reasons. Not that I am strictly opposed to having it, I just don't (yet) see enough value in it.

2025-01-27 23:00 UTC, lucatrv commented on src/field_attributes.rs
> +/// let s = r#" { "i64_or_f64": 1, "f64_or_string": 1 } "#;
Please notice that [serde_json::value](https://docs.rs/serde_json/latest/serde_json/value/enum.Value.html) has the [JSON's numer](https://json-schema.org/understanding-json-schema/reference/numeric#number) field, which includes any numeric type (either integers or floating point numbers). So I think this is correct.

2025-01-30 17:32 UTC, lucatrv commented on src/field_attributes.rs
> +pub fn deserialize_to_type_or_fallback<'de, D, T, F>(
Please look at `rust-csv`'s [`invalid_option` deserializer](https://docs.rs/csv/latest/csv/fn.invalid_option.html), which uses the `Option` type to return valid fields while discarding invalid ones. The approach here is similar, but using the `Result` type we can return both valid and invalid fields. For `rust-csv` I opened a [feature request](https://github.com/BurntSushi/rust-csv/issues/345), which was accepted but still misses an implementation.
Also please notice that since version 0.60.0 [`rust_xlsxwriter` supports `Result` serialization](https://github.com/jmcnamara/rust_xlsxwriter/blob/main/CHANGELOG.md#0600---2023-01-02), and have a look at [`Calamine`'s `deserialize_as_*` helping functions](https://docs.rs/calamine/latest/calamine/fn.deserialize_as_f64_or_string.html?search=deserialize_as).

2025-01-30 17:42 UTC, lucatrv commented on src/field_attributes.rs
> +pub fn deserialize_to_type_or_string_lossy<'de, D, T>(
There is a general `deserialize_to_type_or_fallback`, the `deserialize_to_type_or_string_lossy` is an additional helping function for the most common case where a string fallback is desired.

2025-01-30 17:51 UTC, lucatrv commented on src/field_attributes.rs
> +        T: Deserialize<'de>,
This was just some sugar coding to improve consistency.

2025-01-30 20:01 UTC, lucatrv commented on src/field_attributes.rs
> +    });
I try to recap why I decided to rely on [`serde-value`](https://github.com/arcnmx/serde-value).
Serde's Content API are [private](https://github.com/serde-rs/serde/blob/v1.0.11/serde/src/private/de.rs#L214). There is an ongoing discussion to [make them public](https://github.com/serde-rs/serde/issues/741). At a certain point, it was considered, once `serde-value` was stabilized, to [provide its functionality within Serde](https://github.com/arcnmx/serde-value/issues/16). That is why I thought to rely on it, because once that would happen it should be fairly easily to remove its dependency. However I understand your point since `serde-value`'s development is actually lagging.
I wouldn't however re-implement this functionality within `serde-aux`. Recently a new crate was introduced called [`serde-content`](https://github.com/rushmorem/serde-content) which looks promising, see also this [discussion](https://github.com/serde-rs/serde/issues/2780). So we could move to that. Another option would be to rely on Serde's Content private API.

2025-01-30 20:03 UTC, lucatrv commented
@iddm I think I replied to all your points, please let me know if anything else is needed.

2025-02-10 17:09 UTC, iddm commented on src/field_attributes.rs
> +pub fn deserialize_to_type_or_fallback<'de, D, T, F>(
I apologise for not having looked earlier at your comments. I was on vacation.
So, you think it is easier to have the `Result` type here so that the library can be integrated with the other libraries easier?

2025-02-10 17:14 UTC, iddm requested changes
Thanks again! Just one little minor comment and we are good to go!

2025-02-10 18:14 UTC, lucatrv commented on src/field_attributes.rs
> +pub fn deserialize_to_type_or_fallback<'de, D, T, F>(
Exactly

2025-02-10 18:41 UTC, iddm commented on src/field_attributes.rs
> +pub fn deserialize_to_type_or_fallback<'de, D, T, F>(
Thanks.

2025-02-10 20:18 UTC, lucatrv commented on src/field_attributes.rs
> +    Ok(result)
Please see if my last push is ok

2025-02-10 21:18 UTC, iddm approved these changes

2025-02-10 21:18 UTC, iddm commented on src/field_attributes.rs
> +    Ok(result)
Thanks.

2025-02-10 21:18 UTC, merged

2025-02-10 21:30 UTC, iddm commented
Here it is: https://crates.io/crates/serde-aux/4.6.0